'use strict';
var adm = angular.module('adm', ['ui.router', 'ngFileUpload']);
adm.config(['$stateProvider', '$urlRouterProvider', function($stateProvider, $urlRouterProvider) {
	$urlRouterProvider.otherwise('homepage');
	$stateProvider
	.state("homepage", {
		url:"/homepage",
		views:{
			menu:{
				templateUrl:"menu/homeMenu.html"
			},
			content:{
				templateUrl:"modules/sys.php"
			}
		}	
	})
	.state("uploadimage",{
		url:"/uploadimage",
		views:{
			menu:{
				templateUrl:"menu/homeMenu.html"
			},
			content:{
				templateUrl:"modules/upload-image.html",
				controller:"uploadImage"
			}
		}
	})
	.state("accountlist", {
		url: '/accountlist',
		views:{
			menu:{
				templateUrl:"menu/adminMenu.html"
			},
			content:{
				templateUrl: 'modules/list-account.html',
				controller:"listAccount"
			}
		}
	})
	.state("modifyadm", {
		url: '/modifyadm/:id',
		views:{
			menu:{
				templateUrl:"menu/adminMenu.html"
			},
			content:{
				templateUrl: 'modules/modify-adm.html',
				controller:"modifyadm"
			}
		}
	})
	.state("addadm",{
		url:"/addadm",
		views:{
			menu:{
				templateUrl:"menu/adminMenu.html"
			},
			content:{
				templateUrl: 'modules/add-adm.html',
				controller:"addadm"
			}
		}
	})
	.state("articles",{
		url:"/articles",
		views:{
			menu:{
				templateUrl:"menu/articleMenu.html"
			},
			content:{
				templateUrl:"modules/list-article.html"
			}
		},
		controller:"articles"
	})
	.state("addarticle",{
		url:"/addarticle",
		views:{
			menu:{
				templateUrl:"menu/articleMenu.html"
			},
			content:{
				templateUrl:"modules/add-article.html"
			}
		}	
	})
	.state("cooperate",{
		url:"/cooperate",
		views:{
			menu:{
				templateUrl:"menu/cooperateMenu.html"
			},
			content:{
				templateUrl:"modules/list-cooperate.html"
			}
		}	
	})
	.state("addcooperate",{
		url:"/addcooperate",
		views:{
			menu:{
				templateUrl:"menu/cooperateMenu.html"
			},
			content:{
				templateUrl:"modules/add-cooperate.html",
				controller:"addCooperate"
			}
		}	
	})
	.state("cooperatelist",{
		url:"/cooperatelist",
		views:{
			menu:{
				templateUrl:"menu/cooperateMenu.html"
			},
			content:{
				templateUrl:"modules/list-cooperate.html",
				controller:"addCooperate"
			}
		}	
	});
}]);
